version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /data/web:/data
    restart: always
    container_name: nginx
  php70fpm:
    image: lee/php-fpm:7.0.22
    ports:
      - "9000:9000"
    container_name: php70fpm
  redis32:
    build: ./redis/3.2.10
    ports:
      - "6379:6379"
    volumes:
      - /data/database/redis:/data
    container_name: redis32