version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /data/web:/data
    restart: always
    container_name: nginx
  php70fpm:
    image: lee/php-fpm:7.0.22
    ports:
      - "9000:9000"
    links:
      - "mysql56:mysql56con"
      - "redis32:redis32con"
      - "beanstalk:beanstalkcon"
    volumes:
      - /data/web:/data
    container_name: php70fpm
  mysql56:
    build: ./mysql/5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lpi*hmZB@f6T83*1vS
    volumes:
      - /data/database/mysql/data:/var/lib/mysql
    container_name: mysql56
  redis32:
    build: ./redis/3.2.10
    ports:
      - "6379:6379"
    volumes:
      - /data/database/redis:/data
    container_name: redis32
  beanstalk:
    image: bevand10/alpine-beanstalk:latest
    ports:
      - "11300:11300"
    container_name: beanstalk